[package]
name = "cumments-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
cumments-core.workspace = true

anyhow.workspace = true
async-stream.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
hex.workspace = true
hmac.workspace = true
hickory-resolver.workspace = true
ipnet.workspace = true
rand.workspace = true
reqwest.workspace = true
ruma-common.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
validator.workspace = true

[dev-dependencies]
cumments-store.workspace = true
cumments-matrix.workspace = true
cumments-test-utils.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
serde_yaml_ng.workspace = true
tower.workspace = true
wiremock.workspace = true
