[package]
name = "cumments-api"
version = "0.1.0"
edition = "2021"

[dependencies]
cumments-core = { path = "../cumments-core" }

# Workspace dependencies
anyhow = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sha2.workspace = true
rand.workspace = true
hex.workspace = true
