[package]
name = "cumments-reconciler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cumments-core = { path = "../cumments-core" }
cumments-operator = { path = "../cumments-operator" }

anyhow.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
serde_json.workspace = true
