[package]
name = "cumments-projection"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cumments-core = { version = "0.12.0", path = "../cumments-core" }
matrix-sdk.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
