[package]
name = "cumments"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cumments-api.workspace = true
cumments-core.workspace = true
cumments-matrix.workspace = true
cumments-projector.workspace = true
cumments-reconciler.workspace = true
cumments-store.workspace = true

anyhow.workspace = true
axum.workspace = true
clap.workspace = true
config.workspace = true
dotenvy.workspace = true
hex.workspace = true
matrix-sdk.workspace = true
rand.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
