[package]
name = "cumments"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cumments-api = { path = "../cumments-api" }
cumments-storage = { path = "../cumments-storage" }
cumments-reconciler = { path = "../cumments-reconciler" }
cumments-operator = { path = "../cumments-operator" }
cumments-projector = { path = "../cumments-projector" }
matrix-sdk.workspace = true

anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
sqlx.workspace = true
config.workspace = true
serde.workspace = true
axum.workspace = true
