//! Visitor identity and ownership.
//!
//! Since the architecture treats Matrix as the source of truth, ownership must
//! be publicly verifiable: a visitor holds an **Ed25519 keypair** generated by
//! the browser. The **public key is the identity** and is published in Matrix
//! events; edit/delete requests are authorized by verifying a signature over
//! the request against the stored public key.
//!
//! - `visitor_id`: a short public identifier derived from the public key,
//!   matching the hash segment of the virtual user ID.
//! - Public key and signature are carried in the Matrix event content
//!   (`cumments_public_key` / `cumments_signature`), so ownership survives a
//!   complete rebuild of the read model from the event log.

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use ed25519_dalek::{Signature, VerifyingKey};
use sha2::{Digest, Sha256};

/// Build the canonical message a client signs for a given operation.
///
/// All fields are joined with `\n`; the trailing challenge (the PoW challenge
/// prefix) makes the signature single-use within its expiry window.
pub fn signature_message(parts: &[&str]) -> String {
    parts.join("\n")
}

/// Decode a base64url-encoded Ed25519 public key.
pub fn parse_public_key(public_key_b64: &str) -> Option<VerifyingKey> {
    let bytes = URL_SAFE_NO_PAD.decode(public_key_b64.trim()).ok()?;
    let key: [u8; 32] = bytes.try_into().ok()?;
    VerifyingKey::from_bytes(&key).ok()
}

/// Verify an Ed25519 signature over `message` against `public_key_b64`.
pub fn verify_signature(public_key_b64: &str, message: &str, signature_b64: &str) -> bool {
    let Some(verifying_key) = parse_public_key(public_key_b64) else {
        return false;
    };
    let Ok(sig_bytes) = URL_SAFE_NO_PAD.decode(signature_b64.trim()) else {
        return false;
    };
    let Ok(sig_array): Result<[u8; 64], _> = sig_bytes.try_into() else {
        return false;
    };
    verifying_key
        .verify_strict(message.as_bytes(), &Signature::from_bytes(&sig_array))
        .is_ok()
}

/// Public, stable identifier derived from an Ed25519 public key.
///
/// First 4 bytes of SHA-256 over the raw public key, hex-encoded (8 chars) –
/// same derivation used for the virtual user ID.
pub fn derive_visitor_id_from_public_key(public_key_b64: &str) -> Option<String> {
    let bytes = URL_SAFE_NO_PAD.decode(public_key_b64.trim()).ok()?;
    let hash = Sha256::digest(&bytes);
    Some(hex::encode(&hash[..4]))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};

    #[test]
    fn signature_roundtrip_and_verification() {
        let signing_key = SigningKey::from_bytes(&[7u8; 32]);
        let verifying_key = signing_key.verifying_key();
        let public_key_b64 = URL_SAFE_NO_PAD.encode(verifying_key.to_bytes());

        let message = signature_message(&["POST", "my-blog", "hello", "content", "challenge"]);
        let signature = signing_key.sign(message.as_bytes());
        let signature_b64 = URL_SAFE_NO_PAD.encode(signature.to_bytes());

        assert!(verify_signature(&public_key_b64, &message, &signature_b64));

        // Tampered message must fail.
        assert!(!verify_signature(
            &public_key_b64,
            "tampered",
            &signature_b64
        ));
        // Wrong key must fail.
        let other_key = SigningKey::from_bytes(&[9u8; 32]);
        let other_b64 = URL_SAFE_NO_PAD.encode(other_key.verifying_key().to_bytes());
        assert!(!verify_signature(&other_b64, &message, &signature_b64));
        // Garbage inputs must fail cleanly.
        assert!(!verify_signature("not-a-key", &message, &signature_b64));
        assert!(!verify_signature(
            &public_key_b64,
            &message,
            "not-a-signature"
        ));
    }

    #[test]
    fn visitor_id_is_stable_and_derived_from_public_key() {
        let signing_key = SigningKey::from_bytes(&[7u8; 32]);
        let public_key_b64 = URL_SAFE_NO_PAD.encode(signing_key.verifying_key().to_bytes());

        let a = derive_visitor_id_from_public_key(&public_key_b64).expect("valid key");
        let b = derive_visitor_id_from_public_key(&public_key_b64).expect("valid key");
        assert_eq!(a, b);
        assert_eq!(a.len(), 8);

        let other = SigningKey::from_bytes(&[9u8; 32]);
        let other_b64 = URL_SAFE_NO_PAD.encode(other.verifying_key().to_bytes());
        assert_ne!(
            a,
            derive_visitor_id_from_public_key(&other_b64).expect("valid key")
        );
        assert_eq!(derive_visitor_id_from_public_key("garbage"), None);
    }
}
