//! Visitor identity and ownership.
//!
//! Since the architecture treats Matrix as the source of truth, ownership must
//! be publicly verifiable: a visitor holds an **Ed25519 keypair** generated by
//! the browser. The **public key is the identity** and is published in Matrix
//! events; edit/delete requests are authorized by verifying a signature over
//! the request against the stored public key.
//!
//! - `visitor_id`: a short public identifier derived from the public key,
//!   matching the hash segment of the virtual user ID.
//! - Public key and signature are carried in the Matrix event content
//!   (`host.curious.cumments.public_key` / `host.curious.cumments.signature`),
//!   so ownership survives a complete rebuild of the read model from the event
//!   log.

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use ed25519_dalek::{Signature, VerifyingKey};
use serde::Serialize;
use sha2::{Digest, Sha256};

/// Build the canonical message a client signs for a given operation.
///
/// The message is a JSON array serialized with `serde_json::to_string`.
/// `None` becomes JSON `null`, so absent relations are typed as null
/// rather than an empty string. This makes the format unambiguous even
/// when content contains newlines or quotes, and keeps the namespace
/// minimal — the Matrix `host.curious.cumments.*` block already provides
/// domain separation.
pub fn signature_message(parts: &[Option<&str>]) -> String {
    let values: Vec<serde_json::Value> = parts
        .iter()
        .map(|part| match part {
            Some(text) => serde_json::Value::String((*text).to_string()),
            None => serde_json::Value::Null,
        })
        .collect();
    serde_json::to_string(&values).expect("signature array is valid JSON")
}

/// Build the canonical message signed when posting a comment.
///
/// Covers site, page, content (or mxc URL for media), both reply and thread
/// relations (each as `null` when absent), and the PoW challenge.
/// Includes trailing `1` for the `host.curious.cumments.message` schema.
pub fn post_signature_message(
    site_id: &str,
    page_slug: &str,
    content: &str,
    reply_to: Option<&str>,
    thread_root: Option<&str>,
    challenge: &str,
) -> String {
    signature_message(&[
        Some("POST"),
        Some(site_id),
        Some(page_slug),
        Some(content),
        reply_to.map(|value| value as &str),
        thread_root.map(|value| value as &str),
        Some(challenge),
        Some("1"),
    ])
}

/// Build the canonical message signed for a location share.
/// Includes trailing `1` for the `host.curious.cumments.message` schema.
pub fn locate_signature_message(
    site_id: &str,
    page_slug: &str,
    geo_uri: &str,
    reply_to: Option<&str>,
    thread_root: Option<&str>,
    challenge: &str,
) -> String {
    signature_message(&[
        Some("LOCATE"),
        Some(site_id),
        Some(page_slug),
        Some(geo_uri),
        reply_to.map(|value| value as &str),
        thread_root.map(|value| value as &str),
        Some(challenge),
        Some("1"),
    ])
}

#[derive(Serialize)]
struct PollPayloadForSig<'a> {
    question: &'a str,
    options: &'a [String],
    max_selections: u8,
}

/// Canonical JSON payload for a poll creation signature.
///
/// Deterministically serializes `question`, ordered `options`, and
/// `max_selections` into a single JSON string. The field order is fixed
/// by the struct definition, so the same poll always yields the same
/// string and any change to question / option order / option text /
/// `max_selections` invalidates the signature.
pub fn poll_canonical_payload(question: &str, options: &[String], max_selections: u8) -> String {
    serde_json::to_string(&PollPayloadForSig {
        question,
        options,
        max_selections,
    })
    .expect("poll payload is valid JSON")
}

/// Build the canonical message signed when creating a poll.
///
/// Covers site, page, the canonical poll payload (`question` + ordered
/// `options` + `max_selections`), both reply and thread relations
/// (each as `null` when absent), and the PoW challenge.
/// Includes trailing `1` for the `host.curious.cumments.message` schema.
/// The `max_selections` field is part of the signed payload; the
/// current authoring API only permits `1` (single-select) and the wire
/// format preserves the declared limit.
#[allow(clippy::too_many_arguments)]
pub fn poll_signature_message(
    site_id: &str,
    page_slug: &str,
    question: &str,
    options: &[String],
    max_selections: u8,
    reply_to: Option<&str>,
    thread_root: Option<&str>,
    challenge: &str,
) -> String {
    let payload = poll_canonical_payload(question, options, max_selections);
    signature_message(&[
        Some("POLL"),
        Some(site_id),
        Some(page_slug),
        Some(payload.as_str()),
        reply_to.map(|value| value as &str),
        thread_root.map(|value| value as &str),
        Some(challenge),
        Some("1"),
    ])
}

/// Decode a base64url-encoded Ed25519 public key.
pub fn parse_public_key(public_key_b64: &str) -> Option<VerifyingKey> {
    let bytes = URL_SAFE_NO_PAD.decode(public_key_b64.trim()).ok()?;
    let key: [u8; 32] = bytes.try_into().ok()?;
    VerifyingKey::from_bytes(&key).ok()
}

/// Verify an Ed25519 signature over `message` against `public_key_b64`.
pub fn verify_signature(public_key_b64: &str, message: &str, signature_b64: &str) -> bool {
    let Some(verifying_key) = parse_public_key(public_key_b64) else {
        return false;
    };
    let Ok(sig_bytes) = URL_SAFE_NO_PAD.decode(signature_b64.trim()) else {
        return false;
    };
    let Ok(sig_array): Result<[u8; 64], _> = sig_bytes.try_into() else {
        return false;
    };
    verifying_key
        .verify_strict(message.as_bytes(), &Signature::from_bytes(&sig_array))
        .is_ok()
}

/// Public, stable identifier derived from an Ed25519 public key.
///
/// First 16 bytes of SHA-256 over the raw public key, hex-encoded (32 chars) –
/// same derivation used for the virtual user ID. 128 bits makes collisions
/// infeasible even against adversarial key construction.
pub fn derive_visitor_id_from_public_key(public_key_b64: &str) -> Option<String> {
    let bytes = URL_SAFE_NO_PAD.decode(public_key_b64.trim()).ok()?;
    let hash = Sha256::digest(&bytes);
    Some(hex::encode(&hash[..16]))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};

    #[test]
    fn signature_roundtrip_and_verification() {
        let signing_key = SigningKey::from_bytes(&[7u8; 32]);
        let verifying_key = signing_key.verifying_key();
        let public_key_b64 = URL_SAFE_NO_PAD.encode(verifying_key.to_bytes());

        let message = signature_message(&[
            Some("POST"),
            Some("my-blog"),
            Some("hello"),
            Some("content"),
            Some("challenge"),
        ]);
        let signature = signing_key.sign(message.as_bytes());
        let signature_b64 = URL_SAFE_NO_PAD.encode(signature.to_bytes());

        assert!(verify_signature(&public_key_b64, &message, &signature_b64));

        // Tampered message must fail.
        assert!(!verify_signature(
            &public_key_b64,
            "tampered",
            &signature_b64
        ));
        // Wrong key must fail.
        let other_key = SigningKey::from_bytes(&[9u8; 32]);
        let other_b64 = URL_SAFE_NO_PAD.encode(other_key.verifying_key().to_bytes());
        assert!(!verify_signature(&other_b64, &message, &signature_b64));
        // Garbage inputs must fail cleanly.
        assert!(!verify_signature("not-a-key", &message, &signature_b64));
        assert!(!verify_signature(
            &public_key_b64,
            &message,
            "not-a-signature"
        ));
    }

    #[test]
    fn visitor_id_is_stable_and_derived_from_public_key() {
        let signing_key = SigningKey::from_bytes(&[7u8; 32]);
        let public_key_b64 = URL_SAFE_NO_PAD.encode(signing_key.verifying_key().to_bytes());

        let a = derive_visitor_id_from_public_key(&public_key_b64).expect("valid key");
        let b = derive_visitor_id_from_public_key(&public_key_b64).expect("valid key");
        assert_eq!(a, b);
        assert_eq!(a.len(), 32);

        let other = SigningKey::from_bytes(&[9u8; 32]);
        let other_b64 = URL_SAFE_NO_PAD.encode(other.verifying_key().to_bytes());
        assert_ne!(
            a,
            derive_visitor_id_from_public_key(&other_b64).expect("valid key")
        );
        assert_eq!(derive_visitor_id_from_public_key("garbage"), None);
    }

    #[test]
    fn post_signature_message_includes_reply_and_thread_slots() {
        assert_eq!(
            post_signature_message("my-blog", "hello", "content", Some("$p:hs"), None, "ch"),
            serde_json::to_string(&[
                serde_json::Value::String("POST".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("content".to_string()),
                serde_json::Value::String("$p:hs".to_string()),
                serde_json::Value::Null,
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .expect("valid json")
        );
        assert_eq!(
            post_signature_message("my-blog", "hello", "content", None, None, "ch"),
            serde_json::to_string(&[
                serde_json::Value::String("POST".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("content".to_string()),
                serde_json::Value::Null,
                serde_json::Value::Null,
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .expect("valid json")
        );
        assert_eq!(
            post_signature_message("my-blog", "hello", "content", None, Some("$t:hs"), "ch"),
            serde_json::to_string(&[
                serde_json::Value::String("POST".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("content".to_string()),
                serde_json::Value::Null,
                serde_json::Value::String("$t:hs".to_string()),
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .expect("valid json")
        );
        // Newline in content must not create ambiguity — JSON array handles it.
        let with_newline = post_signature_message("my-blog", "hello", "a\nb", None, None, "ch");
        assert!(with_newline.contains("\\n"));
        assert!(verify_signature(
            &URL_SAFE_NO_PAD.encode(
                SigningKey::from_bytes(&[7u8; 32])
                    .verifying_key()
                    .to_bytes()
            ),
            &with_newline,
            &URL_SAFE_NO_PAD.encode(
                SigningKey::from_bytes(&[7u8; 32])
                    .sign(with_newline.as_bytes())
                    .to_bytes()
            )
        ));
    }

    #[test]
    fn locate_signature_message_includes_both_relations() {
        assert_eq!(
            locate_signature_message(
                "my-blog",
                "hello",
                "geo:1,2",
                Some("$p:hs"),
                Some("$t:hs"),
                "ch"
            ),
            serde_json::to_string(&[
                serde_json::Value::String("LOCATE".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("geo:1,2".to_string()),
                serde_json::Value::String("$p:hs".to_string()),
                serde_json::Value::String("$t:hs".to_string()),
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .expect("valid json")
        );
    }

    #[test]
    fn all_operations_canonical_tuples_match_current_protocol() {
        // 6 operations with trailing "1" (POST/LOCATE/PATCH/REACT/VOTE/POLL) and 3 without (DELETE/UNREACT/QUERY)
        // Challenge must be immediately before "1" where present, and NULL handling must use JSON null.
        assert_eq!(
            post_signature_message("my-blog", "hello", "content", None, None, "ch"),
            serde_json::to_string(&[
                serde_json::Value::String("POST".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("content".to_string()),
                serde_json::Value::Null,
                serde_json::Value::Null,
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            locate_signature_message("my-blog", "hello", "geo:1,2", None, None, "ch"),
            serde_json::to_string(&[
                serde_json::Value::String("LOCATE".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("geo:1,2".to_string()),
                serde_json::Value::Null,
                serde_json::Value::Null,
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            signature_message(&[
                Some("PATCH"),
                Some("my-blog"),
                Some("hello"),
                Some("$c:hs"),
                Some("new content"),
                Some("ch"),
                Some("1"),
            ]),
            serde_json::to_string(&[
                serde_json::Value::String("PATCH".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("$c:hs".to_string()),
                serde_json::Value::String("new content".to_string()),
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            signature_message(&[
                Some("REACT"),
                Some("my-blog"),
                Some("hello"),
                Some("$c:hs"),
                Some("👍"),
                Some("ch"),
                Some("1"),
            ]),
            serde_json::to_string(&[
                serde_json::Value::String("REACT".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("$c:hs".to_string()),
                serde_json::Value::String("👍".to_string()),
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            signature_message(&[
                Some("VOTE"),
                Some("my-blog"),
                Some("hello"),
                Some("$p:hs"),
                Some("opt1"),
                Some("ch"),
                Some("1"),
            ]),
            serde_json::to_string(&[
                serde_json::Value::String("VOTE".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("$p:hs".to_string()),
                serde_json::Value::String("opt1".to_string()),
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            poll_signature_message(
                "my-blog",
                "hello",
                "best?",
                &["A".to_string(), "B".to_string()],
                1,
                None,
                None,
                "ch"
            ),
            serde_json::to_string(&[
                serde_json::Value::String("POLL".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String(poll_canonical_payload(
                    "best?",
                    &["A".to_string(), "B".to_string()],
                    1
                )),
                serde_json::Value::Null,
                serde_json::Value::Null,
                serde_json::Value::String("ch".to_string()),
                serde_json::Value::String("1".to_string()),
            ])
            .unwrap()
        );
        // 3 without trailing "1"
        assert_eq!(
            signature_message(&[
                Some("DELETE"),
                Some("my-blog"),
                Some("hello"),
                Some("$c:hs"),
                Some("ch"),
            ]),
            serde_json::to_string(&[
                serde_json::Value::String("DELETE".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("$c:hs".to_string()),
                serde_json::Value::String("ch".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            signature_message(&[
                Some("UNREACT"),
                Some("my-blog"),
                Some("hello"),
                Some("$c:hs"),
                Some("👍"),
                Some("ch"),
            ]),
            serde_json::to_string(&[
                serde_json::Value::String("UNREACT".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
                serde_json::Value::String("$c:hs".to_string()),
                serde_json::Value::String("👍".to_string()),
                serde_json::Value::String("ch".to_string()),
            ])
            .unwrap()
        );
        assert_eq!(
            signature_message(&[Some("QUERY_COMMENTS"), Some("my-blog"), Some("hello")]),
            serde_json::to_string(&[
                serde_json::Value::String("QUERY_COMMENTS".to_string()),
                serde_json::Value::String("my-blog".to_string()),
                serde_json::Value::String("hello".to_string()),
            ])
            .unwrap()
        );
    }

    #[test]
    fn poll_signature_covers_all_security_sensitive_fields() {
        let signing_key = SigningKey::from_bytes(&[7u8; 32]);
        let public_key_b64 = URL_SAFE_NO_PAD.encode(signing_key.verifying_key().to_bytes());
        let base = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["A".to_string(), "B".to_string()],
            1,
            None,
            None,
            "ch",
        );
        let sig = URL_SAFE_NO_PAD.encode(signing_key.sign(base.as_bytes()).to_bytes());
        assert!(verify_signature(&public_key_b64, &base, &sig));
        // Tampered question must fail.
        let tampered_q = poll_signature_message(
            "my-blog",
            "hello",
            "other?",
            &["A".to_string(), "B".to_string()],
            1,
            None,
            None,
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &tampered_q, &sig));
        // Tampered option text must fail.
        let tampered_opt = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["A".to_string(), "C".to_string()],
            1,
            None,
            None,
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &tampered_opt, &sig));
        // Tampered option order must fail.
        let reordered = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["B".to_string(), "A".to_string()],
            1,
            None,
            None,
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &reordered, &sig));
        // Tampered max_selections must fail.
        let tampered_max = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["A".to_string(), "B".to_string()],
            2,
            None,
            None,
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &tampered_max, &sig));
        // Reply/thread are part of the signature.
        let with_reply = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["A".to_string(), "B".to_string()],
            1,
            Some("$p:hs"),
            None,
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &with_reply, &sig));
        let with_thread = poll_signature_message(
            "my-blog",
            "hello",
            "best?",
            &["A".to_string(), "B".to_string()],
            1,
            None,
            Some("$t:hs"),
            "ch",
        );
        assert!(!verify_signature(&public_key_b64, &with_thread, &sig));
    }

    #[test]
    fn poll_canonical_payload_is_deterministic() {
        let a = poll_canonical_payload("q", &["x".to_string(), "y".to_string()], 1);
        let b = poll_canonical_payload("q", &["x".to_string(), "y".to_string()], 1);
        assert_eq!(a, b);
        let swapped = poll_canonical_payload("q", &["y".to_string(), "x".to_string()], 1);
        assert_ne!(a, swapped);
        let c = poll_canonical_payload("q", &["x".to_string()], 1);
        assert_ne!(a, c);
    }

    /// A signature bound to one semantic relation combination must verify
    /// only for that exact combination: changing either relation, adding a
    /// relation, or removing one must invalidate it. `thread_root` (Thread
    /// membership) and `reply_to` (direct parent) are signed independently —
    /// neither is derived from the other, and no wire-level detail such as
    /// `is_falling_back` participates (the canonical payloads above pin the
    /// exact slot lists, so any extra field would break them).
    fn assert_relation_combinations_bind<F>(build: F)
    where
        F: Fn(Option<&str>, Option<&str>) -> String,
    {
        let signing_key = SigningKey::from_bytes(&[11u8; 32]);
        let public_key_b64 = URL_SAFE_NO_PAD.encode(signing_key.verifying_key().to_bytes());
        let combinations = [
            (None, None),
            (None, Some("$t:hs")),
            (Some("$p:hs"), None),
            (Some("$p:hs"), Some("$t:hs")),
        ];
        for (reply_to, thread_root) in combinations {
            let message = build(reply_to, thread_root);
            let signature = URL_SAFE_NO_PAD.encode(signing_key.sign(message.as_bytes()).to_bytes());
            assert!(
                verify_signature(&public_key_b64, &message, &signature),
                "unchanged relations must verify: reply_to={reply_to:?} thread_root={thread_root:?}"
            );
            for (other_reply, other_thread) in combinations {
                let tampered = build(other_reply, other_thread);
                let unchanged = (other_reply, other_thread) == (reply_to, thread_root);
                assert_eq!(
                    verify_signature(&public_key_b64, &tampered, &signature),
                    unchanged,
                    "signed reply_to={reply_to:?} thread_root={thread_root:?} must \
                     {}verify against reply_to={other_reply:?} thread_root={other_thread:?}",
                    if unchanged { "" } else { "not " }
                );
            }
        }
    }

    #[test]
    fn post_signature_binds_each_relation_combination() {
        assert_relation_combinations_bind(|reply_to, thread_root| {
            post_signature_message("my-blog", "hello", "content", reply_to, thread_root, "ch")
        });
    }

    #[test]
    fn locate_signature_binds_each_relation_combination() {
        assert_relation_combinations_bind(|reply_to, thread_root| {
            locate_signature_message("my-blog", "hello", "geo:1,2", reply_to, thread_root, "ch")
        });
    }

    #[test]
    fn poll_signature_binds_each_relation_combination() {
        assert_relation_combinations_bind(|reply_to, thread_root| {
            poll_signature_message(
                "my-blog",
                "hello",
                "best?",
                &["A".to_string(), "B".to_string()],
                1,
                reply_to,
                thread_root,
                "ch",
            )
        });
    }
}
