[package]
name = "cumments-matrix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cumments-core.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
matrix-sdk.workspace = true
tokio.workspace = true
tracing.workspace = true
