[package]
name = "cumments-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
cumments-core = { path = "../cumments-core" }
chrono = { workspace = true }

# Workspace dependencies
anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
